# -----------------------------------------------
# vagrant.yml for VirtualBox
# -----------------------------------------------
shared:
  vm_name: 'node'
  vm_count: 2
  mem_size: 8192
  cpus: 2
  prefix_name: vgt-ol7-rac
  # ---------------------------------------------
  domain: localdomain
  public_subnet:  192.168.56.100
  private_subnet: 192.168.200.100
  vip_subnet:     192.168.56.110
  private_netname: '-priv'
  vip_netname:     '-vip'
  scan_ip1: 192.168.56.121
  scan_ip2: 192.168.56.122
  scan_ip3: 192.168.56.123
  # ---------------------------------------------
  non_rotational: 'on'
  asm_disk_path:
  asm_disk_num: 4
  asm_disk_size: 20
  p1_ratio: 80
  # ---------------------------------------------
## -----------------------------------------------
## vagrant.yml for libVirt
## Uncomment the following for KVM
## -----------------------------------------------
#  storage_pool_name: Vagrant_KVM_Storage
## -----------------------------------------------

env:
  provider: virtualbox
## -----------------------------------------------
## vagrant.yml for libVirt
## Comment preceding line
## Uncomment the following for KVM
## -----------------------------------------------
#  provider: libvirt
## -----------------------------------------------
  # ---------------------------------------------
  gi_software:     LINUX.X64_193000_grid_home.zip
  db_software:     LINUX.X64_193000_db_home.zip
  # ---------------------------------------------
  root_password:   welcome1
  grid_password:   welcome1
  oracle_password: welcome1
  sys_password:    welcome1
  pdb_password:    welcome1
  # ---------------------------------------------
  ora_languages:   en,en_GB
  # ---------------------------------------------
  nomgmtdb:        true
  orestart:        false
  # ---------------------------------------------
  db_name:         DB193H1
  pdb_name:        PDB1
  db_type:         RAC
  cdb:             false
  # ---------------------------------------------

