#│▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
#
# LICENSE UPL 1.0
#
# Copyright (c) 1982-2020 Oracle and/or its affiliates. All rights reserved.
#
#    NAME
#      vagrantfile
#
#    DESCRIPTION
#      Creates Oracle RAC (Real Application Cluster) Vagrant virtual machines for KVM/libVirt & VirtualBox
#
#    NOTES
#      DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
#    AUTHOR
#      Ruggero Citton - RAC Pack, Cloud Innovation and Solution Engineering Team
#
#    MODIFIED   (MM/DD/YY)
#    sscott      07/15/21 - Add support for multi-node RAC
#    rcitton     09/23/20 - Latest OL7 (7.8.142) box for VirtualBox  is having only one disk
#    rcitton     03/30/20 - VBox libvirt & kvm support
#    rcitton     03/24/20 - Creation
#
#    REVISION
#    20210715 - $Revision: 2.0.2.4 $
#
#│▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│

### -------------------------------------------------------------------
### Disclaimer:
###
### EXCEPT WHERE EXPRESSLY PROVIDED OTHERWISE, THE INFORMATION, SOFTWARE,
### PROVIDED ON AN \"AS IS\" AND \"AS AVAILABLE\" BASIS. ORACLE EXPRESSLY DISCLAIMS
### ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT
### LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
### PURPOSE AND NON-INFRINGEMENT. ORACLE MAKES NO WARRANTY THAT: (A) THE RESULTS
### THAT MAY BE OBTAINED FROM THE USE OF THE SOFTWARE WILL BE ACCURATE OR
### RELIABLE; OR (B) THE INFORMATION, OR OTHER MATERIAL OBTAINED WILL MEET YOUR
### EXPECTATIONS. ANY CONTENT, MATERIALS, INFORMATION OR SOFTWARE DOWNLOADED OR
### OTHERWISE OBTAINED IS DONE AT YOUR OWN DISCRETION AND RISK. ORACLE SHALL HAVE
### NO RESPONSIBILITY FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT
### RESULTS FROM THE DOWNLOAD OF ANY CONTENT, MATERIALS, INFORMATION OR SOFTWARE.
###
### ORACLE RESERVES THE RIGHT TO MAKE CHANGES OR UPDATES TO THE SOFTWARE AT ANY
### TIME WITHOUT NOTICE.
###
### Limitation of Liability:
###
### IN NO EVENT SHALL ORACLE BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
### SPECIAL OR CONSEQUENTIAL DAMAGES, OR DAMAGES FOR LOSS OF PROFITS, REVENUE,
### DATA OR USE, INCURRED BY YOU OR ANY THIRD PARTY, WHETHER IN AN ACTION IN
### CONTRACT OR TORT, ARISING FROM YOUR ACCESS TO, OR USE OF, THE SOFTWARE.
### -------------------------------------------------------------------
### This script is NOT supported by Oracle World Wide Technical Support.
### The script has been tested and appears to work as intended.
### -------------------------------------------------------------------

# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'
require 'ipaddr'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Vagrant Boxes Source Definition
var_box = 'oraclelinux/7'
var_url = 'https://oracle.github.io/vagrant-projects/boxes/oraclelinux/7.json'

puts ""
puts "│▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│"
puts " Oracle RAC (Real Application Cluster) Vagrant box for KVM/libVirt or VirtualBox  "
puts " Copyright (c) 1982-2020 Oracle and/or its affiliates                             "
puts "----------------------------------------------------------------------------------"
puts " Author: Ruggero Citton <ruggero.citton@oracle.com>                               "
puts "         RAC Pack, Cloud Innovation and Solution Engineering Team                 "
puts "│▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│"
puts ""
puts ""

# -----------------------------------------------------------------
# Variables
# -----------------------------------------------------------------
params = YAML.load_file 'config/vagrant.yml'
#
var_provider_name   = params['env']['provider']
var_vm_name         = params['shared']['vm_name']
var_vm_count        = params['shared']['vm_count']
var_mem_size        = params['shared']['mem_size']
var_cpus            = params['shared']['cpus']
var_prefix_name     = params['shared']['prefix_name']
#
var_domain          = params['shared']['domain']
var_public_subnet   = params['shared']['public_subnet']
var_public_lan      = (var_public_subnet.rpartition(".")[0])
var_public_octet    = (var_public_subnet.rpartition(".")[-1])
var_private_subnet  = params['shared']['private_subnet']
var_private_lan     = (var_private_subnet.rpartition(".")[0])
var_private_octet   = (var_private_subnet.rpartition(".")[-1])
var_vip_subnet      = params['shared']['vip_subnet']
var_private_netname = params['shared']['private_netname']
var_vip_netname     = params['shared']['vip_netname']
var_scan_ip1        = params['shared']['scan_ip1']
var_scan_ip2        = params['shared']['scan_ip2']
var_scan_ip3        = params['shared']['scan_ip3']
#
var_vm_storage      = params['shared']['storage_pool_name']
#
var_asm_storage     = params['shared']['storage_pool_name']
var_asm_disk_num    = params['shared']['asm_disk_num']
var_asm_disk_size   = params['shared']['asm_disk_size']
var_p1_ratio        = params['shared']['p1_ratio']
#
var_gi_software     = params['env']['gi_software']
var_gi_software_ver = (var_gi_software.split("_"))[1].to_i
#
var_db_software     = params['env']['db_software']
var_db_software_ver = (var_db_software.split("_"))[1].to_i
#
var_ora_languages   = params['env']['ora_languages']
#
var_root_password   = params['env']['root_password']
var_grid_password   = params['env']['grid_password']
var_oracle_password = params['env']['oracle_password']
var_sys_password    = params['env']['sys_password']
var_pdb_password    = params['env']['pdb_password']
#
var_nomgmtdb        = params['env']['nomgmtdb']
var_orestart        = params['env']['orestart']
#
var_db_name         = params['env']['db_name']
var_pdb_name        = params['env']['pdb_name']
var_db_type         = params['env']['db_type']
var_cdb             = params['env']['cdb']

var_asm_lib_type    = 'ASMLIB'

# -----------------------------------------------------------------
# Provider specific checks
# -----------------------------------------------------------------
if ( (var_provider_name != 'libvirt') and (var_provider_name != 'virtualbox') )
  puts "ERROR: 'provider' option can be 'libvirt' or 'virtualbox'"
  exit
else
  provider = (var_provider_name).to_sym
  puts "--------------------"
  puts "Detected #{provider}"
  puts "--------------------"
end

# Base Settings
if var_provider_name == 'virtualbox'
  ENV['VAGRANT_DEFAULT_PROVIDER'] || 'virtualbox'
  box_disks_num = 1
elsif var_provider_name == 'libvirt'
  box_disks_num = 1
  ENV['VAGRANT_DEFAULT_PROVIDER'] || 'libvirt'
  ENV['VAGRANT_NO_PARALLEL'] = 'yes'
else
  puts "Not supported #{provider}, exiting..."
  exit
end

## Storage Setup
if var_provider_name == 'libvirt'
  var_vm_storage      = params['shared']['storage_pool_name']
  var_asm_storage     = params['shared']['storage_pool_name']

  if var_vm_storage.to_s.empty?
    var_vm_storage = "default"
  end
  if var_asm_storage.to_s.empty?
    var_asm_storage = "default"
  end
else
  var_group           = "/" + var_prefix_name
  var_non_rotational  = params['shared']['non_rotational']
  var_asm_storage     = params['shared']['asm_disk_path']

  if ( (var_non_rotational != 'on') and (var_non_rotational != 'off') )
    puts 'ERROR: non_rotational option can be on or off'
    exit
  end

  if var_asm_storage.to_s.empty?
    var_asm_storage = "./"
  else
    var_asm_storage = var_asm_storage + "/"
  end
end

# -----------------------------------------------------------------
# Variables check
# -----------------------------------------------------------------
if !var_prefix_name.match? /\A[0-9a-zA-Z-]{1,14}\z/
  puts 'ERROR: prefix_name \'' + var_prefix_name + '\' option can be any combination'
  puts '  {1..13 chars} of lower and uppercase alphanumeric characters (a - z, A - Z, 0 - 9), and hyphen(-)'
  exit
end

if var_mem_size.to_i < 6144
  puts 'ERROR: vm_mem_size option can not be less then 6 Gb'
  exit
end

if ( (var_nomgmtdb != true) and (var_nomgmtdb != false) )
  puts 'ERROR: nomgmtdb option can be true or false'
  exit
end
if ( (var_orestart != true) and (var_orestart != false) )
  puts 'ERROR: orestart option can be true or false'
  exit
end
if ! var_vm_count.between?(1, 8)
  puts 'ERROR: vm_count must be between 1 and 8'
  exit
end
if ( (var_cdb != true) and (var_cdb != false) )
  puts 'ERROR: cdb option can be true or false'
  exit
end

if ( (var_orestart == true) and (var_db_type != 'SI'))
  puts 'ERROR: orestart option supports only Single Instance database'
  exit
end
if ( (var_orestart == true) and (var_vm_count > 1))
  puts 'ERROR: orestart option only supports vm_count of 1'
  exit
end
if ( (var_db_type != 'RAC') and (var_db_type != 'RACONE') and (var_db_type != 'SI'))
  puts 'ERROR: db_type option can be RAC, RACONE or SI'
  exit
end
if ( (var_db_type == 'RAC') and (var_vm_count < 2))
  puts 'ERROR: RAC db_type requires vm_count > 1'
  exit
end
if ( (var_db_type == 'RACONE') and (var_vm_count > 1))
  puts 'ERROR: RACONE db_type requires vm_count = 1'
  exit
end
if ( (var_asm_lib_type != 'ASMLIB') and (var_asm_lib_type != 'ASMFD') )
  puts 'ERROR: asm_lib_type option can be ASMLIB or ASMFD'
  exit
end
if ! var_p1_ratio.between?(10, 80)
  puts 'ERROR: p1_ratio option can be an integer between 10 and 80'
  exit
end

if var_asm_disk_num.to_i < 4
  puts 'ERROR: asm_disk_num option can not be less then 4'
  exit
end
if var_asm_disk_size.to_i < 10
  puts 'ERROR: asm_disk_size option can not be less then 10 Gb'
  exit
end

class String
  def is_ip?
    !!IPAddr.new(self) rescue false
  end
end

if ! var_public_subnet.is_ip?
  puts 'ERROR: public_subnet is not a valid IP address'
  exit
end
if ! var_private_subnet.is_ip?
  puts 'ERROR: private_subnet is not a valid IP address'
  exit
end
if ! var_vip_subnet.is_ip?
  puts 'ERROR: vip_subnet is not a valid IP address'
  exit
end
if ! var_scan_ip1.is_ip?
  puts 'ERROR: scan_ip1 for is not a valid IP address'
  exit
end
if ! var_scan_ip2.is_ip?
  puts 'ERROR: scan_ip3 for is not a valid IP address'
  exit
end
if ! var_scan_ip3.is_ip?
  puts 'ERROR: scan_ip3 for is not a valid IP address'
  exit
end

if var_db_name.to_s.empty?
 puts "ERROR: db_name is not defined"
 exit
end

if var_root_password.to_s.empty?
 puts "ERROR: root_password is not defined"
 exit
end
if var_grid_password.to_s.empty?
 puts "ERROR: grid_password is not defined"
  exit
end
if var_oracle_password.to_s.empty?
 puts "ERROR: oracle_password is not defined"
 exit
end
if var_sys_password.to_s.empty?
 puts "ERROR: sys_password is not defined"
 exit
end

if (var_cdb == true)
  if var_pdb_name.to_s.empty?
   puts "ERROR: pdb_name is not defined"
   exit
  end
  if var_pdb_password.to_s.empty?
   puts "ERROR: pdb_password is not defined"
   exit
  end
end

path = "./ORCL_software/" + var_gi_software
if ! File.exist?(path)
  puts "ERROR: gi_software does not exist"
  exit
end
path = "./ORCL_software/" + var_db_software
if ! File.exist?(path)
  puts "ERROR: db_software does not exist"
  exit
end

#------------------------------------------------------------------

# Install required Vagrant plugin
unless Vagrant.has_plugin?("vagrant-reload")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-reload')
end
unless Vagrant.has_plugin?("vagrant-proxyconf")
  puts 'Installing vagrant-proxyconf Plugin...'
  system('vagrant plugin install vagrant-proxyconf')
end

if var_provider_name == 'libvirt'
  unless Vagrant.has_plugin?("vagrant-libvirt")
    puts 'Installing vagrant-libvirt Plugin...'
    system('vagrant plugin install vagrant-libvirt')
  end
  unless Vagrant.has_plugin?("vagrant-kvm")
    puts 'Installing vagrant-kvm Plugin...'
    system('vagrant plugin install vagrant-kvm')
  end
end

# Get host time zone for setting VM time zone
offset_sec = Time.now.gmt_offset
if (offset_sec % (60 * 60)) == 0
  offset_hr = ((offset_sec / 60) / 60)
  timezone_suffix = offset_hr >= 0 ? "-#{offset_hr.to_s}" : "+#{(-offset_hr).to_s}"
  var_system_timezone = 'Etc/GMT' + timezone_suffix
else
  # if host time zone isn't an integer hour offset, fall back to UTC
  var_system_timezone = 'UTC'
end

# VMs definition
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = var_box
  config.vm.box_url = var_url

  if var_provider_name == 'virtualbox'
    config.vm.box_version = ">= 7.8.142"
  end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  # add proxy configuration from host env - optional
  if Vagrant.has_plugin?("vagrant-proxyconf")
    puts "getting Proxy Configuration from Host..."
    if ENV["http_proxy"]
      puts "http_proxy: " + ENV["http_proxy"]
      config.proxy.http     = ENV["http_proxy"]
    end
    if ENV["https_proxy"]
      puts "https_proxy: " + ENV["https_proxy"]
      config.proxy.https    = ENV["https_proxy"]
    end
    if ENV["no_proxy"]
      config.proxy.no_proxy = ENV["no_proxy"]
    end
  end

  config.ssh.forward_x11 = true
  # Enable ssh password authentication
  config.vm.provision "shell", inline: <<-SHELL
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    /bin/systemctl restart sshd
  SHELL

  # Enable provisioning with a shell script
  config.vm.provision "shell", path: "scripts/setup.sh", env: {
      "PROVIDER"           => var_provider_name,
      "BOX_DISK_NUM"       => box_disks_num,
      "SYSTEM_TIMEZONE"    => var_system_timezone,
      "PREFIX_NAME"        => var_prefix_name,
      "GI_SOFTWARE"        => var_gi_software,
      "GI_SOFTWARE_VER"    => var_gi_software_ver,
      "DB_SOFTWARE"        => var_db_software,
      "DB_SOFTWARE_VER"    => var_db_software_ver,
      "ORA_LANGUAGES"      => var_ora_languages,
      "VM_NAME"            => var_vm_name,
      "VM_COUNT"           => var_vm_count,
      "CPUS"               => var_cpus,
      "MEM_SIZE"           => var_mem_size,
      "PUBLIC_SUBNET"      => var_public_subnet,
      "PRIVATE_SUBNET"     => var_private_subnet,
      "PRIVATE_NETNAME"    => var_private_netname,
      "VIP_SUBNET"         => var_vip_subnet,
      "VIP_NETNAME"        => var_vip_netname,
      "SCAN_IP1"           => var_scan_ip1,
      "SCAN_IP2"           => var_scan_ip2,
      "SCAN_IP3"           => var_scan_ip3,
      "DOMAIN"             => var_domain,
      "ROOT_PASSWORD"      => var_root_password,
      "GRID_PASSWORD"      => var_grid_password,
      "ORACLE_PASSWORD"    => var_oracle_password,
      "SYS_PASSWORD"       => var_sys_password,
      "PDB_PASSWORD"       => var_pdb_password,
      "P1_RATIO"           => var_p1_ratio,
      "ASM_LIB_TYPE"       => var_asm_lib_type,
      "NOMGMTDB"           => var_nomgmtdb,
      "ORESTART"           => var_orestart,
      "DB_NAME"            => var_db_name,
      "PDB_NAME"           => var_pdb_name,
      "DB_TYPE"            => var_db_type,
      "CDB"                => var_cdb
  }

  (1..var_vm_count).each do |i|
    i = var_vm_count+1-i # Work backwards through the nodes
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = var_vm_name + "#{i}"
      if i == var_vm_count
        doasm = true # Only run ASM setup on the last node
      end
      if var_provider_name == 'virtualbox'
        node.vm.network :private_network, ip: var_public_lan.to_s + "." + (var_public_octet.to_i + i).to_s, virtualbox__hostonly: "vboxnet0"
        node.vm.network :private_network, ip: var_private_lan.to_s + "." + (var_private_octet.to_i + i).to_s, virtualbox__intnet: "private"
        build_vb(node, var_prefix_name + "-" + "var_vm_name#{i}", var_mem_size, var_cpus, var_group, box_disks_num, node.vm.hostname + "_u01.vdi", doasm, var_asm_disk_num, var_asm_storage, var_asm_disk_size, var_non_rotational)
      else # else libvirt
        node.vm.network "private_network", :libvirt__network_name => "vgt-hostonly_network", ip: var_public_lan.to_s + "." + (var_public_octet.to_i + i).to_s
        node.vm.network "private_network", :libvirt__network_name => "vgt-private_network",  ip: var_private_lan.to_s + "." + (var_private_octet.to_i + i).to_s
        build_kvm(node, var_prefix_name, var_mem_size, var_cpus, box_disks_num, var_vm_storage, doasm, var_asm_disk_num, var_asm_storage, var_asm_disk_size)
      end # End var_provider_name == 'virtualbox'
    end # End do |node|
  end # End node loop
end

def build_vb(node, name, memory, cpus, group, vm_disks, vm_storage, doasm, asm_disks_num, asm_storage, asm_disk_size, nonrotational)
  node.vm.provider "virtualbox" do |vb|
    vb.name   = name
    vb.memory = memory
    vb.cpus   = cpus
    vb.customize ["modifyvm", :id, "--groups", group] unless group.nil?

    disk_num = 0
    while disk_num < vm_disks do
      vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', disk_num, '--nonrotational', nonrotational]
      disk_num += 1
    end

    # Make u01 vdisk
    unless File.exist?(vm_storage)
      vb.customize ['createhd', '--filename', vm_storage, '--size', 100 * 1024]
    end # End unless File.exist?(vm_storage)
    vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', disk_num, '--device', 0, '--type', 'hdd', '--medium', vm_storage, '--nonrotational', nonrotational]
    disk_num = disk_num.to_i + 1

    # Make asm disks
    num = 0
    while num < asm_disks_num do
      asm_disk = asm_storage + "asm_disk" + num.to_s + ".vdi"
      if doasm == true
        unless File.exist?(asm_disk)
          vb.customize ['createhd', '--filename', asm_disk, '--size', asm_disk_size * 1024, '--format', 'VDI', '--variant', 'Fixed']
        end # End unless File.exist?(asm_disk)
        vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', disk_num, '--device', 0, '--type', 'hdd', '--medium', asm_disk, '--mtype', 'shareable', '--nonrotational', nonrotational]
        vb.customize ['modifymedium', 'disk', asm_disk, '--type', 'shareable']
      else
        vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', disk_num, '--device', 0, '--type', 'hdd', '--medium', asm_disk, '--mtype', 'shareable', '--nonrotational', nonrotational]
      end # End doasm == true
      disk_num += 1
      num += 1
    end # End while num < asm_disk_num do
  end
end

def build_kvm(node, default_prefix, memory, cpus, vm_disks, vm_storage, doasm, asm_disks_num, asm_storage, asm_disk_size)
  node.vm.provider "libvirt" do |libvirt|
    libvirt.default_prefix = default_prefix
    libvirt.driver = "kvm"
    libvirt.memory = memory
    libvirt.cpus   = cpus
    libvirt.storage_pool_name = vm_storage

    # Make vdisks
    disk_num = 0
    while disk_num < vm_disks do
      libvirt.storage :file,
        :size => '100G'      # defaults to 10G if unspecified!
      disk_num += 1
    end # End while disk_num < box_disks_num do

    disk_num = disk_num.to_i + 1
    libvirt.storage_pool_name = asm_storage

    # Make asm disks
    num = 0
    while num < asm_disks_num do
      asm_disk = asm_storage + "asm_disk" + num.to_s + ".vdi"
      asm_disk_size = asm_disk_size.to_s + "G"
      if doasm == true
        libvirt.storage :file,
          :path => prefix_name + '_asm_' + num.to_s,
          :size => asm_disk_size,  # defaults to 10G if unspecified!
          :cache => 'none',
          :type => 'raw',               # defaults to 'qcow2' if unspecified!
          :shareable => 'true'
      else
        libvirt.storage :file,
          :path => prefix_name + '_asm_' + num.to_s,
          :size => asm_disk_size,  # defaults to 10G if unspecified!
          :cache => 'none',
          :type => 'raw',               # defaults to 'qcow2' if unspecified!
          :allow_existing => 'true',
          :shareable => 'true'
      end # End doasm == true
      disk_num += 1
      num += 1
    end # End while num < asm_disk_num do
  end
end
#----------------------------------------------------------
# EndOfFile
#----------------------------------------------------------
